### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by knifeworm** [GallearTech/VexPanel_v1#1]
Everytime i try and access stuff on the panel like servers and stuff like that it throws an error but when i look at the code to see about this error it has something to do with a licence key? can anyone help me on this

**Comment by The-MG** [comment]
Hello! If you can provide the error that'd be great. And it can't be the licenses because all of our license code has been removed from GitHub. 

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
@The-MG Looking at the code i can see that is not the case 
![image](https://user-images.githubusercontent.com/77696553/124650486-b7c99e00-de91-11eb-9792-7745c79076ae.png)
There is still code about license keys there

**Comment by The-MG** [comment]
> @The-MG Looking at the code i can see that is not the case
> ![image](https://user-images.githubusercontent.com/77696553/124650486-b7c99e00-de91-11eb-9792-7745c79076ae.png)
> There is still code about license keys there

Strange. This was most likely `manage` API code which was used for the old Vex Manager. But again, a picture of the error you got would be really helpful.

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
There is not really much off an error it legit just says ERR

**Comment by The-MG** [comment]
May I know the page that the error occurred on? E.g. https://example.com/admin/servers.php.

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
The error apears the admin pages and server creation pages

**Comment by The-MG** [comment]
Yeah, again a screen shot of the error would be helpful as we have no code that displays the code `ERR` as far as I can see right now. 

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
Yes u do 
![image](https://user-images.githubusercontent.com/77696553/124658851-2f9cc600-de9c-11eb-8a74-2ddf3acc0c42.png)

**Comment by The-MG** [comment]
Those are all in old `manage` API that was used for the old Vex Manager. If you fail to comply and send a screen shot of the error that you are getting on the admin pages, we are going to close this issue.

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
![image](https://user-images.githubusercontent.com/77696553/124659263-a934b400-de9c-11eb-9d55-2b74aa227ddb.png)

**Comment by The-MG** [comment]
Are you in a API folder? Or the admin page? Because if you're in an admin page, it shouldn't be a white screen with just `ERR` on it. If you are in an API file, the API isn't used to be access by URL (unless in /api/web), the other API is used by bots, and in the `manage` API case, our old Vex Manager. 

Thanks,
Gallear Technologies!

**Comment by knifeworm** [comment]
Oh never mind im a bit dumb i was trying to access the api file like a dumb dumb and didn't notice
